version: 2.1

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies
      - unit_tests:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - unit_tests
          filters:
            branches:
              only: master

#############################################################
# Define jobs
#############################################################
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build