version: 2.1

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies
      - deploy:
          requires:
            - install_dependencies
          filters:
            branches:
              only: master

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    working_directory: ~/app
    docker:
      - image: node:10.15-slim
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
