version: 2.1

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
      - deploy:
          requires:
            - build
            - test
          #filters:
          #  branches:
          #    only:
          #      - main

#############################################################
# Define jobs
#############################################################
jobs:

  build:
    working_directory: ~/app
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build Solution
          command: dotnet build --configuration Release --output dist
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test:
    working_directory: ~/app
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Install Project Dependencies
          command: dotnet restore
      - run:
          name: Run Unit Tests
          command: dotnet test

  deploy:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install bash and curl
          command: |
            apk update
            apk add -y curl
            apk add -y bash
            apk add -y zip
            apk update
            apk upgrade
      - run:
          name: Install CLI
          command: |
            apk add --update python python-dev py-pip build-base
            pip install awscli
      - run:
          name: Set Credentials
          command: |          
            aws configure set region us-east-1
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - run:
          name: "Replace Environment Variables"
          command: |
            chmod +x environment-variables.sh
            ./environment-variables.sh
      - run:
          name: Create Zip
          command: |
            cd ./dist/
            zip -r function.zip .
            cp function.zip ../function.zip
      #- run:
      #    name: Deploy AWS Lambda
      #    command: aws lambda update-function-code --function-name feed-me-lambda --zip-file fileb://dist/function.zip
