version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master

#############################################################
# Define jobs
#############################################################
jobs:
  install_dependencies:
    working_directory: ~/app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: chmod +x pack.sh
      - run: ./pack.sh
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    context: aws
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy AWS Lambda
          command: aws update-function-code --function-name feed-me-lambda --zip-file function.zip