version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

#############################################################
# Define workflows
#############################################################
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - unit_tests
      - build_image:
          requires:
            - build
            - unit_tests

#############################################################
# Define jobs
#############################################################
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet build

  unit_tests:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run:
          name: Build solution
          command: dotnet test

  build_image:
    docker:
      - image: docker:17.05.0-ce-git 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build solution
          command: docker build -t feed-me-api .
